# Generated by Django 6.1 on 2026-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('service', models.CharField(choices=[('Flight Booking', 'Flight Booking'), ('Holiday Travel', 'Holiday Travel'), ('Visa Assistance', 'Visa Assistance'), ('Accommodation', 'Accommodation'), ('Other', 'Other')], max_length=50)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
